apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "beekeeper.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "beekeeper.labels" . | nindent 4 }}
data:
  config.yaml: |
    serve:
      {{- toYaml .Values.serve | nindent 6 }}
    watch:
      interval: {{ .Values.watch.interval | quote }}
