package machine

import (
	"os"
	"path/filepath"
	"testing"
)

func TestParseOllamaLoads(t *testing.T) {
	journal := `time=2026-09-30T16:34:22.164+03:00 level=INFO source=llama_server.go:434 msg="starting llama-server" cmd="/usr/lib/ollama/llama-server --model /var/lib/ollama/blobs/sha256-small --port 44597 --host 127.0.0.1"
[GIN] 2026/09/30 - 16:35:49 | 200 |         1m27s |      172.21.0.3 | POST     "/v1/chat/completions"
time=2026-09-30T16:40:51.432+03:00 level=INFO source=llama_server.go:434 msg="starting llama-server" cmd="/usr/lib/ollama/llama-server --model /var/lib/ollama/blobs/sha256-big --port 40001"
[GIN] 2026/09/30 - 16:40:52 | 200 | 512.1ms |      172.21.0.3 | POST     "/v1/chat/completions"
[GIN] 2026/09/30 - 16:41:20 | 200 | 29.436412014s |      172.21.0.2 | POST     "/api/chat"`
	got := ParseOllamaLoads(journal)
	if got["/var/lib/ollama/blobs/sha256-small"] != "172.21.0.3" {
		t.Errorf("small loaded by %q", got["/var/lib/ollama/blobs/sha256-small"])
	}
	// The first request after the big load started after it: the loader
	// is the one that was already running.
	if got["/var/lib/ollama/blobs/sha256-big"] != "172.21.0.2" {
		t.Errorf("big loaded by %q", got["/var/lib/ollama/blobs/sha256-big"])
	}
}

func TestParseOllamaLoadsInFlight(t *testing.T) {
	// The lab loaded the model and its request ended; the host loads it
	// again and its request still runs: no POST names that load yet.
	journal := `time=2026-09-30T17:20:00.000+02:00 level=INFO source=llama_server.go:434 msg="starting llama-server" cmd="/usr/lib/ollama/llama-server --model /var/lib/ollama/blobs/sha256-mid --port 40001"
[GIN] 2026/09/30 - 17:20:30 | 200 | 31s |      172.21.0.3 | POST     "/v1/chat/completions"
time=2026-09-30T17:36:40.000+02:00 level=INFO source=llama_server.go:434 msg="starting llama-server" cmd="/usr/lib/ollama/llama-server --model /var/lib/ollama/blobs/sha256-mid --port 40002"`
	if c, ok := ParseOllamaLoads(journal)["/var/lib/ollama/blobs/sha256-mid"]; ok {
		t.Errorf("an in-flight load is attributed to %q, the earlier load's client", c)
	}
}

func TestModelBlob(t *testing.T) {
	mf := "# Modelfile generated by \"ollama show\"\nFROM /var/lib/ollama/blobs/sha256-dec5\nTEMPLATE {{ .Prompt }}\n"
	if got := modelBlob(mf); got != "/var/lib/ollama/blobs/sha256-dec5" {
		t.Errorf("blob = %q", got)
	}
	if got := modelBlob("FROM qwen3:30b\n"); got != "" {
		t.Errorf("blob of a non-blob FROM = %q", got)
	}
}

func TestReadGPUs(t *testing.T) {
	dir := t.TempDir()
	dev := filepath.Join(dir, "card1", "device")
	if err := os.MkdirAll(dev, 0o750); err != nil {
		t.Fatal(err)
	}
	for f, v := range map[string]string{
		"mem_info_gtt_used":   "45097156608\n",
		"mem_info_gtt_total":  "46208954368\n",
		"mem_info_vram_used":  "8049176576\n",
		"mem_info_vram_total": "8589934592\n",
	} {
		if err := os.WriteFile(filepath.Join(dev, f), []byte(v), 0o600); err != nil {
			t.Fatal(err)
		}
	}
	g := readGPUs(filepath.Join(dir, "card*", "device", "mem_info_gtt_used"))
	if len(g) != 1 || g[0].Device != "card1" || g[0].GTTUsedMiB != 43008 || g[0].GTTTotalMiB != 44068 || g[0].VRAMTotMiB != 8192 {
		t.Fatalf("gpus = %+v", g)
	}
	if GTTUsedMiB(g) != 43008 {
		t.Errorf("GTTUsedMiB = %d", GTTUsedMiB(g))
	}
	if readGPUs(filepath.Join(dir, "none*", "mem_info_gtt_used")) != nil {
		t.Error("a machine without amdgpu has GPUs")
	}
}
