// Package crd embeds the CustomResourceDefinitions of beekeeper.giantswarm.io,
// generated by controller-gen from pkg/apis (make generate-crds).
package crd

import "embed"

// Files are the CRD manifests, one per kind.
//
//go:embed *.yaml
var Files embed.FS
